name: default
channels:
- conda-forge
- nodefaults
dependencies:
- numpy <=2.0
- matplotlib-base >=3.10.5,<4
- earthaccess >=0.14.0,<0.15
- cdsapi >=0.7.6,<0.8
- ecmwf-api-client >=1.6.5,<2
- xarray >=2025.8.0,<2026
- rasterio >=1.4.3,<2
- snowexsql >=0.5.0,<0.6
- scipy >=1.16.1,<2
- rioxarray >=0.19.0,<0.20
- geopandas >=1.1.1,<2
- pandas >=2.3.2,<3
- shapely >=2.1.1,<3
- sqlalchemy >=2.0.43,<3
- cartopy >=0.25.0,<0.26
- sliderule >=4.18.1,<5
- boto3 >=1.39.11,<2
- jupyter >=1.1.1,<2
- ipympl >=0.9.7,<0.10
- ipykernel >=6.30.1,<7
- geoalchemy2 >=0.18.0,<0.19
- contextily >=1.6.2,<2
- cmcrameri >=1.9,<2
- seaborn >=0.13.2,<0.14
- s3fs >=2025.7.0,<2026
- holoviews >=1.18.3,<2
- geoviews >=1.5.0,<2
- hvplot >=0.10.0,<0.11
- fsspec >=2025.7.0,<2026
- datashader >=0.18.2,<0.19
- panel >=1.2.3,<2
- param >=1.13.0,<2
- bokeh >=3.1.1,<4
- folium >=0.20.0,<0.21
- earthpy >=0.9.4,<0.10
- netcdf4 >=1.7.2,<2
- h5py >=3.14.0,<4
- icepyx >=1.3.0,<2
- pyproj >=3.7.2,<4
- mystmd
- jupyterlab-myst
- pip
- pip:
  - snowmicropyn>=1.2.1, <2
  - uavsar-pytools>=0.7.1, <0.8

